# Generated by Django 4.2 on 2025-10-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=50)),
                ('usernme', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
